# version: "3"

# services:
#   neo4j:
#     image: neo4j
#     ports: 
#       - 7474:7474
#       - 7687:7687
#     volumes: 
#       - ./data:/data
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deploy
  labels:
    app: neo4j-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-pod
  template:
    metadata:
      labels: 
        app: neo4j-pod
    spec:
      containers:
      - name: neo4j
        image: neo4j
        imagePullPolicy: IfNotPresent
        ports:
          - name: bolt
            containerPort: 7687
          - name: http
            containerPort: 7474
        volumeMounts:
          - mountPath: /data
            name: ps
      volumes:
      - name: ps
        hostPath:
          type: DirectoryOrCreate
          path: /neo4j_data
