apiVersion: v1
kind: Service
metadata:
  name: neo4j-svc
  labels: 
    name: neo4j-svc
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
  selector:
    app: neo4j-pod